### ISSUE TITLE
Is it possible to pass data to dataSources asynchronously?

### ISSUE THREAD

**Issue by ekafyi** [ConProgramming/junglejs#10]
Trying JungleJS for the first time now, good work!

I wonder if it's possible to query data from an external source (eg. `fetch` from external API) then pass it to `dataSources` `items`? 

The problem is, it has to be done asynchronously. Is it possible at all to return `exports` in `jungle.config.js` asynchronously? Or is there any other way to achieve this?

Thanks!

**Comment by ConProgramming** [comment]
The goal is to have this work as a plugin some day (not requiring users to edit the boilerplate code), but for now you can achieve it with the following:

To `jungle.config.js`,  I made these edits
```javascript
...

const fetch = require('node-fetch');

...

module.exports = async () => {
    const bookRes = await fetch('https://openlibrary.org/api/books?bibkeys=ISBN:0201558025,LCCN:93005405&format=json');

    return {
        ...
        dataSources: [
            {
                format: "json", name: "book", items: Object.values(await bookRes.json()),
            },
            ...
        ]
    }
};
```

To `app.js`, I made these edits
```javascript

...

const getJungleConfig = require('./jungle.config');
...
getJungleConfig().then(jungleConfig => {
    startGraphqlServer(jungleConfig, __dirname, () => readRoutes(jungleConfig, app, __dirname).then(() => stopGraphqlServer(() => startAppServer(app))));
})
```
Since `jungle.config.js` is now returning an async function, you can use await and interact with async functions and work with data however you need to before returning your fetched data along with the rest of the config. 

Great question, and thanks for enjoying the project! Let me know if this doesn't work right for you 👍

**Comment by ekafyi** [comment]
Thank you for the answer, @ConProgramming! Going to try this when I have time. (Feel free to close the issue if you want.)

**Comment by stordahl** [comment]
Is there any reason I'm getting this error when following the solution above?
```
(node:2735) UnhandledPromiseRejectionWarning: TypeError: paramOption.split is not a function
```
It starts up the graphql server just fine, and I can console.log the data I'm fetching, but it errors out after that.

**Comment by ConProgramming** [comment]
> Is there any reason I'm getting this error when following the solution above?
> 
> ```
> (node:2735) UnhandledPromiseRejectionWarning: TypeError: paramOption.split is not a function
> ```
> 
> It starts up the graphql server just fine, and I can console.log the data I'm fetching, but it errors out after that.

It's probably something with the name of your dynamic route file (the `[param].svelte` file) and whatever your `QUERYPARAMOPTS` is....  I should be able to see whats wrong from those two

**Comment by stordahl** [comment]
```
const QUERYPARAMOPTS = `
	query {
		sanityPosts {
			slug {
				current
			}
		}
	}
`;
```
I just changed the route name to [current].svelte, which threw a different error: 
```
(node:4088) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
```

**Comment by ConProgramming** [comment]
> ```
> const QUERYPARAMOPTS = `
> 	query {
> 		sanityPosts {
> 			slug {
> 				current
> 			}
> 		}
> 	}
> `;
> ```
> 
> I just changed the route name to [current].svelte, which threw a different error:
> 
> ```
> (node:4088) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
> ```

Hmm right now it's only setup to get the route variable as a root field (so current being nested inside of slug is whats breaking it here :/)... 

You can work around this in your `dataSources` though with `.map` or something on the items for sanityPosts
Or if you prefer not to edit your sanityPosts source you can make always make another source with just thats just like `sanityPostSlugs`

But yep ***in the future*** should be able to name a file like `[slug_current]` and get this to work

**Comment by stordahl** [comment]
I've changed the Sanity schema so slug is just a string in the top level of the returned object. Take a look at @stordahl/jungle-sanity and let me know if you see any glaring issues! I'm getting a graphql error now, but the dynamic pages are being rendered now!

**Comment by ConProgramming** [comment]
> I've changed the Sanity schema so slug is just a string in the top level of the returned object. Take a look at @stordahl/jungle-sanity and let me know if you see any glaring issues! I'm getting a graphql error now, but the dynamic pages are being rendered now!

Awesome! Never worked with Sanity before but nice to know you can do that. And yep I'll make sure to clone it later tonight and poke around!

**Comment by floer32** [comment]
I really think the docs should emphasize this. I'll make a PR. Thanks all for helping me get unblocked 👍

**Comment by floer32** [comment]
Hmm, I switched to `async () => { ... get data ... return { ... dataSources: [...] } }` and now I'm getting:

```
junglejs-site/node_modules/junglejs/index.js:254
        dataSources.forEach(source => {
                    ^

TypeError: Cannot read property 'forEach' of undefined    at generateSchema (junglejs-site/node_modules/junglejs/index.js:254:14)
```

I'll keep debugging but I really think a simple first-party example should be included in the junglejs `template`. Maybe I can pull code from one of the examples above, and combine it with the official junglejs template, and make a PR.

**Comment by stordahl** [comment]
@hangtwenty Please submit a PR or at least share more of your jungle.config.js so we can see what's going on

**Comment by floer32** [comment]
OK, thanks for the suggestion, I'm shy with that sometimes (need to get used to it because it's not fun for me to post something without an example, my bad)

**Comment by stordahl** [comment]
No worries, I totally understand!

**Comment by floer32** [comment]
Main thing was the jungleConfig -> getJungleConfig part -- I thought I

made that change but I missed one var or arg in the config, and only in

app.js or build.json. So yeah my mistake.

(I'll make a PR to the template)
