### ISSUE TITLE
_layout & <slot> similar to Sapper

### ISSUE THREAD

**Issue by stordahl** [ConProgramming/junglejs#15]
It would be *great* to implement layout components, is this something being considered?

**Comment by ConProgramming** [comment]
I've thought about this actually, yes! But I think it would be better to have it closer to how [Routify](https://routify.dev/guide/introduction/structure) does it. The _layout is great but I think having a _reset would be useful too.

Haven't had a chance to look into how Routify/Sapper do it, but I'm guessing they just process it into a slot? But I wanted to think through if layouts could be improved in Jungle in any way before adding them...

**Comment by stordahl** [comment]
_reset would be slick! I'll poke around in the sapper code base when I have some time to see if I can find any inspiration ✨
